### ISSUE TITLE
Having lots elements makes the page scroll and reveals grey background.

### ISSUE THREAD

**Issue by francescortiz** [kalutheo/elm-ui-explorer#31]
It would be great that when there are a lot of items in the sidebar you got a scroll instead of the page growing. I think that switching to `display: grid;` for the general layout would be helpful.

**Comment by francescortiz** [comment]
This scss fixes the situation and provides independent scrollbars for the list of stories and the stories themselves.

```scss
body {
  background-color: white;

  > .uie-h-screen {
    display: flex;
    flex-direction: column;
    height: 100vh;
    overflow: hidden;
    > .uie-flex {
      height: 100%;

      > div {
        overflow: auto;
      }
    }
  }
}
```

**Comment by kalutheo** [comment]
hey @francescortiz that's true .  I experienced that too. I will add that to the next version

**Comment by francescortiz** [comment]
Good. Thank you

**Comment by francescortiz** [comment]
I improved the snippet. The old one would make the scrolling bars finish outside the window, which made the last two stories not accessible:

```scss
body {
  background-color: white;

  > .uie-h-screen {
    display: flex;
    flex-direction: column;
    height: 100vh;
    overflow: hidden;
    > .uie-flex {
      height: 100%;

      &:last-child {
        height: calc(100vh - 60px);
        overflow: hidden;
      }

      > div {
        height: 100% !important;
        overflow: auto;
      }
    }
  }
}

```
